# This is a basic workflow to help you get started with Actions

name: Deploy files

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Upload to Azure blob storage
        env:
          BLOB_STORAGE_CONNSTRING: ${{ secrets.BLOB_STORAGE_CONNSTRING }}
        # You may pin to the exact commit or the version.
        # uses: bacongobbler/azure-blob-storage-upload@779a18b594a1a7cf5412645e06c856324a8b01e5
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          # The connection string for the storage account
          connection_string: $BLOB_STORAGE_CONNSTRING
          # The name of the storage account container these assets will be uploaded to
          container_name: files
          # The name of the directory you want to upload
          source_dir: files
